# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "n_iter", # <cpr_iter_test>
  "rand_comm", # <cpr_iter_test>
  "obs_val", # <get_ses>
  "random_values", # <get_ses>
  "rand_mean", # <get_ses>
  "rand_sd", # <get_ses>
  "obs_c_upper", # <get_ses>
  "obs_q", # <get_ses>
  "obs_c_lower", # <get_ses>
  NULL
))
