# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "mishler_endem_cols", # <cpr_make_pal>
  "cpr_endem_cols", # <cpr_make_pal>
  "cpr_endem_cols_2", # <cpr_make_pal>
  "mishler_signif_cols", # <cpr_make_pal>
  "cpr_signif_cols", # <cpr_make_pal>
  "cpr_signif_cols_2", # <cpr_make_pal>
  "obs_val", # <get_ses>
  "random_values", # <get_ses>
  "rand_mean", # <get_ses>
  "rand_sd", # <get_ses>
  "obs_c_upper", # <get_ses>
  "obs_q", # <get_ses>
  "obs_c_lower", # <get_ses>
  NULL
))
